---
namespace: "tcharl"
name: "ansible_container_registry"
version: "1.0.1"
description: "Setup container registry"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-container-registry"
documentation: "https://github.com/OsgiliathEnterprise/ansible-container-registry/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible-container-registry"
issues: "https://github.com/OsgiliathEnterprise/ansible-container-registry/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "docker-repository"
  - "container registry"
