---

- name: Install docker
  ansible.builtin.import_role:
    name: tcharl.ansible_containerization

- name: Install prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

- name: Start nginx-proxy
  ansible.builtin.include_tasks: nginx-proxy.yml

- name: Start docker-registry
  ansible.builtin.include_tasks: docker-registry.yml
