---

- name: ansible-container-registry | nginx-proxy | open 80 port
  ansible.builtin.include_role:
    name: tcharl.ansible_routing
  vars:
    firewalld_zones:
      - name: public
        enabled_ports:
          - port: 80
            protocol: tcp
          - port: 80
            protocol: tcp

- name: ansible-container-registry | nginx-proxy | open 443 port
  ansible.builtin.include_role:
    name: tcharl.ansible_routing
  when: gen_certs
  vars:
    firewalld_zones:
      - name: public
        enabled_ports:
          - port: 443
            protocol: tcp
          - port: 443
            protocol: tcp

- name: ansible-container-registry | nginx-proxy | configure virtualhost
  include_role:
    name: tcharl.ansible_routing
  when: gen_certs
  vars:
    virtual_hosts:
      - name: "{{ container_registry_domain_name }}"
        ports_binding:
          - "80:80" # mandatory for letsencrypt
          - "443:443"
        gen_certs: yes
