---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
    roles-path: ../community
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  flake8
  ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community ANSIBLE_COLLECTIONS_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community-collections ansible-lint
platforms:
  - name: Fedora-Molecule-Container-registry-VB
    box: tcharl/fedora-33-cgroupv1
    provider_options:
      cpus: 2
      memory: 2048
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE Controller', '--hostiocache', 'on']"
    provider_override_args:
      - "persistent_storage.enabled = true"
      - "persistent_storage.location = 'molecule-container-registry.vdi'"
      - "persistent_storage.size = 2000"
      - "persistent_storage.mount = false"
      - "persistent_storage.diskdevice = '/dev/sdb'"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../community:${ANSIBLE_ROLES_PATH}:${MOLECULE_PROJECT_DIRECTORY}/..
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 3
