---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    requirements-file: requirements-collections.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: idm.osgiliath.test
    box: ${TESTBOX:-bento/fedora-42}
    provider_options:
      driver: "kvm"
      cpus: 4
      memory: 4096
    provider_raw_config_args:
      - "storage :file, :size => '1G', :device => 'vdb'"
    groups:
      - ipaservers
  - name: client.osgiliath.test
    box: ${TESTBOX:-bento/fedora-42}
    provider_options:
      driver: "kvm"
      cpus: 4
      memory: 4096
    provider_raw_config_args:
      - "storage :file, :size => '1G', :device => 'vdb'"
    groups:
      - ipaclients
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../community-collections:${ANSIBLE_COLLECTIONS_PATH}"
    ANSIBLE_REMOTE_TMP: /var/tmp/ansible-remote
    ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
  options:
    vvv: True
  config_options:
    defaults:
      remote_tmp: /var/tmp/ansible-remote
      forks: 20
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=600s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: kvm
