---
- name: Converge
  hosts: client.osgiliath.test
  vars:
    preferred_nic: "eth1"
    company_domain: osgiliath.test
    secure_logs: False
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb1
        create: true
        lvmetanames:
          - lvname: thinpool
            size: 40%VG
            opts: "--wipesignatures y"
            create: true
            metadata: non-persistent/thinpoolmeta
            autoextendtreshold: 80
            autoextendpercent: 20
            filesystem: xfs
            mntp: /var/lib/docker
            mount: true
            mopts: defaults,pquota,gquota,quota
          - lvname: thinpoolmeta
            size: 10%VG
            opts: "--wipesignatures y"
            create: true
    manage_lvm: true
    gen_certs: false
    hostname: "containers.dummy.com"
  roles:
    - role: tcharl.ansible_container_registry
